### PR TITLE
Leaderboard set up project

### PR DESCRIPTION
**Pull request by businesskaniki**
## leaderboard  set-up project changes :recycle: 

- added webpack
- added basic HTML 
- added CSS file
- added linters
- added git flow
- modified readme file

***happy review :laughing:***

### CODE REVIEW

**Review by elyor-doniyorov — CHANGES_REQUESTED** [review]
Hi @businesskaniki, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
✅ Descriptive PR title and description
✅ Use of webpack to bundle JavaScript
✅ All webpack related packages are included in `package.json`

## Required Changes ♻️
- [ ] Kindly use [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md) instead of GitHub flow.
- [ ] Kindly modify your Readme file by adding descriptive project title, description, built with technologies and Getting started section. Because this gives first impression about your project.

_Do not check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by KayLemba — CHANGES_REQUESTED** [review]
Hi @businesskaniki    👋
Good job so far working on the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight 🎉
No linter errors. ✔️
GitHub flow is followed. ✔️

Required Changes ♻️
Check the comments under the review in the inline comments.
 - Please kindly use Git flow instead of Github flow please implement this change as requested 
  by previous code reviewer thankyou. 

Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by businesskaniki** [comment]
## @KayLemba  

***suggestion***

- that is what I did but if ni create another branch with something like ```git flow feature start html-css ```I will have to make another pr  which will not be good

- so please consider that :pray: :pleading_face:

**Comment by KayLemba** [comment]
> ## @KayLemba
> _**suggestion**_
> 
> * that is what I did but if ni create another branch with something like `git flow feature start html-css `I will have to make another pr  which will not be good
> * so please consider that pray pleading_face

You are supposed to have a development branch and you are supposed to name the branch dev or development please go through the requirements properly

**Comment by KayLemba** [comment]
And your default branch is supposed to be the development branch not your master branch

**Comment by businesskaniki** [comment]
## I have added the dev  and made it the default branch
***but still detaching this branch from master to dev is impossible without opening a new pr :pray: :pleading_face:***

**Review by BertrandConxy — CHANGES_REQUESTED** [review]
Hello @businesskaniki ✋ , 

Great work on making the changes requested by a previous reviewer like improving your README to look more professional 👏 👏 
You've done well implementing some of the requested changes, but there is still **ONE** which isn't addressed yet but I know this time you are going to get important information that will help you achieve it 😉 🏃‍♂️ 

 ## Highlights 💪 
- Nice README
- good PR description
- no linter errors

 ## Required Changes ♻️

- [ ] As the previous reviewers suggested, you need to use the `git flow`. That means you need to merge from the feature branch into the `dev` branch that you have created instead of the master branch. Answering to the confusion you have as you said in the comments, **I can assure you that you can change the base branch in which you want to merge changes right here in this pull request.** You **don't need to open a new pull request**. PLease watch this [LOOM VIDEO](https://www.loom.com/share/be0a657bdcbf4b0390f7501529232f35) I recorded showing you how you can change the base branch from master to dev 💡 💡 😃 Please try it out and see what you can achieve 😉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by dasileker — APPROVED** [review]
### **Hi @businesskaniki,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
